[theme]
# Primary accent color for interactive elements.
primaryColor = "#eda832"

# Background color for the main content area.
backgroundColor = "#14292eff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#253033ff"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"